#Operates in Paris
environment   = "staging"
region        = "eu-west-3"
credentials   = "~/.aws/credentials"
ami_id        = "ami-087855b6c8b59a9e4"
open_internet = "0.0.0.0/0"
key_pair      = "Example"
instance_type = "t2.micro"
asg_start     = "00 10 * * *"
asg_stop      = "00 15 * * *"
